export const LOAD_USERS_START = "LOAD_USERS_START";
export const LOAD_USERS_SUCCESS = "LOAD_USERS_SUCCESS";
export const LOAD_USERS_ERROR = "LOAD_USERS_ERROR";

export const CREATE_USERS_START = "CREATE_USERS_START";
export const CREATE_USERS_SUCCESS = "CREATE_USERS_SUCCESS";
export const CREATE_USERS_ERROR = "CREATE_USER_ERROR";

export const DELETE_USERS_START = "DELETE_USERS_START";
export const DELETE_USERS_SUCCESS = "DELETE_USERS_SUCCESS";
export const DELETE_USERS_ERROR = "DELETE_USER_ERROR";

export const LOGIN_USERS_START = "LOGIN_USERS_START";
export const LOGIN_USERS_SUCCESS = "LOGIN_USERS_SUCCESS";
export const LOGIN_USERS_ERROR = "LOGIN_USERS_ERROR";

export const LOGOUT_USERS_START = "LOGOUT_USERS_START";
export const LOGOUT_USERS_SUCCESS = "LOGOUT_USERS_SUCCESS";
export const LOGOUT_USERS_ERROR = "LOGOUT_USERS_ERROR";
